opt_in_rules: # some rules are only opt-in
  - empty_count
  - closure_spacing
  - closure_end_indentation
  - conditional_returns_on_newline
  - explicit_init
  - missing_docs
  # Find all the available rules by running:
  # swiftlint rules
included: # paths to include during linting. `--path` is ignored if present.
  - EverythingCounter
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
  - Source/ExcludedFolder
  - Source/ExcludedFile.swift
  - Source/*/ExcludedFile.swift # Exclude files with a wildcard
analyzer_rules: # Rules run by `swiftlint analyze` (experimental)
  - explicit_self