name: Test

on:
  push:
    branches:
      - master
      - v2
  pull_request:
    branches:
      - master
      - v2

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Select Xcode 13.2.1
      run: sudo xcode-select -s /Applications/Xcode_13.2.1.app
    - name: Run tests
      run: make test
      
